// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Router

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CloseTransportRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCloseTransportRequest(buf []byte, offset flatbuffers.UOffsetT) *CloseTransportRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CloseTransportRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCloseTransportRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCloseTransportRequest(buf []byte, offset flatbuffers.UOffsetT) *CloseTransportRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CloseTransportRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCloseTransportRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CloseTransportRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CloseTransportRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CloseTransportRequest) TransportId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CloseTransportRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CloseTransportRequestAddTransportId(builder *flatbuffers.Builder, transportId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(transportId), 0)
}
func CloseTransportRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
