// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtxStream

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RtxDump struct {
	_tab flatbuffers.Table
}

func GetRootAsRtxDump(buf []byte, offset flatbuffers.UOffsetT) *RtxDump {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RtxDump{}
	x.Init(buf, n+offset)
	return x
}

func FinishRtxDumpBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRtxDump(buf []byte, offset flatbuffers.UOffsetT) *RtxDump {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RtxDump{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRtxDumpBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RtxDump) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RtxDump) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RtxDump) Params(obj *Params) *Params {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Params)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RtxDumpStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RtxDumpAddParams(builder *flatbuffers.Builder, params flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(params), 0)
}
func RtxDumpEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
