// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Notification

import "strconv"

type Body byte

const (
	BodyNONE                                               Body = 0
	BodyTransport_SendRtcpNotification                     Body = 1
	BodyTransport_SctpStateChangeNotification              Body = 2
	BodyProducer_SendNotification                          Body = 3
	BodyDataProducer_SendNotification                      Body = 4
	BodyTransport_TraceNotification                        Body = 5
	BodyWebRtcTransport_IceSelectedTupleChangeNotification Body = 6
	BodyWebRtcTransport_IceStateChangeNotification         Body = 7
	BodyWebRtcTransport_DtlsStateChangeNotification        Body = 8
	BodyPlainTransport_TupleNotification                   Body = 9
	BodyPlainTransport_RtcpTupleNotification               Body = 10
	BodyDirectTransport_RtcpNotification                   Body = 11
	BodyProducer_ScoreNotification                         Body = 12
	BodyProducer_TraceNotification                         Body = 13
	BodyProducer_VideoOrientationChangeNotification        Body = 14
	BodyConsumer_LayersChangeNotification                  Body = 15
	BodyConsumer_RtpNotification                           Body = 16
	BodyConsumer_ScoreNotification                         Body = 17
	BodyConsumer_TraceNotification                         Body = 18
	BodyDataConsumer_MessageNotification                   Body = 19
	BodyDataConsumer_BufferedAmountLowNotification         Body = 20
	BodyActiveSpeakerObserver_DominantSpeakerNotification  Body = 21
	BodyAudioLevelObserver_VolumesNotification             Body = 22
)

var EnumNamesBody = map[Body]string{
	BodyNONE:                                               "NONE",
	BodyTransport_SendRtcpNotification:                     "Transport_SendRtcpNotification",
	BodyTransport_SctpStateChangeNotification:              "Transport_SctpStateChangeNotification",
	BodyProducer_SendNotification:                          "Producer_SendNotification",
	BodyDataProducer_SendNotification:                      "DataProducer_SendNotification",
	BodyTransport_TraceNotification:                        "Transport_TraceNotification",
	BodyWebRtcTransport_IceSelectedTupleChangeNotification: "WebRtcTransport_IceSelectedTupleChangeNotification",
	BodyWebRtcTransport_IceStateChangeNotification:         "WebRtcTransport_IceStateChangeNotification",
	BodyWebRtcTransport_DtlsStateChangeNotification:        "WebRtcTransport_DtlsStateChangeNotification",
	BodyPlainTransport_TupleNotification:                   "PlainTransport_TupleNotification",
	BodyPlainTransport_RtcpTupleNotification:               "PlainTransport_RtcpTupleNotification",
	BodyDirectTransport_RtcpNotification:                   "DirectTransport_RtcpNotification",
	BodyProducer_ScoreNotification:                         "Producer_ScoreNotification",
	BodyProducer_TraceNotification:                         "Producer_TraceNotification",
	BodyProducer_VideoOrientationChangeNotification:        "Producer_VideoOrientationChangeNotification",
	BodyConsumer_LayersChangeNotification:                  "Consumer_LayersChangeNotification",
	BodyConsumer_RtpNotification:                           "Consumer_RtpNotification",
	BodyConsumer_ScoreNotification:                         "Consumer_ScoreNotification",
	BodyConsumer_TraceNotification:                         "Consumer_TraceNotification",
	BodyDataConsumer_MessageNotification:                   "DataConsumer_MessageNotification",
	BodyDataConsumer_BufferedAmountLowNotification:         "DataConsumer_BufferedAmountLowNotification",
	BodyActiveSpeakerObserver_DominantSpeakerNotification:  "ActiveSpeakerObserver_DominantSpeakerNotification",
	BodyAudioLevelObserver_VolumesNotification:             "AudioLevelObserver_VolumesNotification",
}

var EnumValuesBody = map[string]Body{
	"NONE":                                               BodyNONE,
	"Transport_SendRtcpNotification":                     BodyTransport_SendRtcpNotification,
	"Transport_SctpStateChangeNotification":              BodyTransport_SctpStateChangeNotification,
	"Producer_SendNotification":                          BodyProducer_SendNotification,
	"DataProducer_SendNotification":                      BodyDataProducer_SendNotification,
	"Transport_TraceNotification":                        BodyTransport_TraceNotification,
	"WebRtcTransport_IceSelectedTupleChangeNotification": BodyWebRtcTransport_IceSelectedTupleChangeNotification,
	"WebRtcTransport_IceStateChangeNotification":         BodyWebRtcTransport_IceStateChangeNotification,
	"WebRtcTransport_DtlsStateChangeNotification":        BodyWebRtcTransport_DtlsStateChangeNotification,
	"PlainTransport_TupleNotification":                   BodyPlainTransport_TupleNotification,
	"PlainTransport_RtcpTupleNotification":               BodyPlainTransport_RtcpTupleNotification,
	"DirectTransport_RtcpNotification":                   BodyDirectTransport_RtcpNotification,
	"Producer_ScoreNotification":                         BodyProducer_ScoreNotification,
	"Producer_TraceNotification":                         BodyProducer_TraceNotification,
	"Producer_VideoOrientationChangeNotification":        BodyProducer_VideoOrientationChangeNotification,
	"Consumer_LayersChangeNotification":                  BodyConsumer_LayersChangeNotification,
	"Consumer_RtpNotification":                           BodyConsumer_RtpNotification,
	"Consumer_ScoreNotification":                         BodyConsumer_ScoreNotification,
	"Consumer_TraceNotification":                         BodyConsumer_TraceNotification,
	"DataConsumer_MessageNotification":                   BodyDataConsumer_MessageNotification,
	"DataConsumer_BufferedAmountLowNotification":         BodyDataConsumer_BufferedAmountLowNotification,
	"ActiveSpeakerObserver_DominantSpeakerNotification":  BodyActiveSpeakerObserver_DominantSpeakerNotification,
	"AudioLevelObserver_VolumesNotification":             BodyAudioLevelObserver_VolumesNotification,
}

func (v Body) String() string {
	if s, ok := EnumNamesBody[v]; ok {
		return s
	}
	return "Body(" + strconv.FormatInt(int64(v), 10) + ")"
}
