{
 "title": "mediasoup",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ice",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "increase(ice_count[1m])" }
   ]
  },
  {
   "title": "rtp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "increase(rtp_count[1m])" }
   ]
  },
  {
   "title": "rtcp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "increase(rtcp_count[1m])" }
   ]
  },
  {
   "title": "mediasoup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "increase(mediasoup_count[1m])" }
   ]
  },
  {
   "title": "keyframe",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "increase(keyframe_count[1m])" }
   ]
  }
 ]
}