// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Response

import "strconv"

type Body byte

const (
	BodyNONE                                   Body = 0
	BodyWorker_DumpResponse                    Body = 1
	BodyWorker_ResourceUsageResponse           Body = 2
	BodyWebRtcServer_DumpResponse              Body = 3
	BodyRouter_DumpResponse                    Body = 4
	BodyTransport_ProduceResponse              Body = 5
	BodyTransport_ConsumeResponse              Body = 6
	BodyTransport_RestartIceResponse           Body = 7
	BodyPlainTransport_ConnectResponse         Body = 8
	BodyPlainTransport_DumpResponse            Body = 9
	BodyPlainTransport_GetStatsResponse        Body = 10
	BodyPipeTransport_ConnectResponse          Body = 11
	BodyPipeTransport_DumpResponse             Body = 12
	BodyPipeTransport_GetStatsResponse         Body = 13
	BodyDirectTransport_DumpResponse           Body = 14
	BodyDirectTransport_GetStatsResponse       Body = 15
	BodyWebRtcTransport_ConnectResponse        Body = 16
	BodyWebRtcTransport_DumpResponse           Body = 17
	BodyWebRtcTransport_GetStatsResponse       Body = 18
	BodyProducer_DumpResponse                  Body = 19
	BodyProducer_GetStatsResponse              Body = 20
	BodyConsumer_DumpResponse                  Body = 21
	BodyConsumer_GetStatsResponse              Body = 22
	BodyConsumer_SetPreferredLayersResponse    Body = 23
	BodyConsumer_SetPriorityResponse           Body = 24
	BodyDataProducer_DumpResponse              Body = 25
	BodyDataProducer_GetStatsResponse          Body = 26
	BodyDataConsumer_GetBufferedAmountResponse Body = 27
	BodyDataConsumer_DumpResponse              Body = 28
	BodyDataConsumer_GetStatsResponse          Body = 29
	BodyDataConsumer_SetSubchannelsResponse    Body = 30
	BodyDataConsumer_AddSubchannelResponse     Body = 31
	BodyDataConsumer_RemoveSubchannelResponse  Body = 32
)

var EnumNamesBody = map[Body]string{
	BodyNONE:                                   "NONE",
	BodyWorker_DumpResponse:                    "Worker_DumpResponse",
	BodyWorker_ResourceUsageResponse:           "Worker_ResourceUsageResponse",
	BodyWebRtcServer_DumpResponse:              "WebRtcServer_DumpResponse",
	BodyRouter_DumpResponse:                    "Router_DumpResponse",
	BodyTransport_ProduceResponse:              "Transport_ProduceResponse",
	BodyTransport_ConsumeResponse:              "Transport_ConsumeResponse",
	BodyTransport_RestartIceResponse:           "Transport_RestartIceResponse",
	BodyPlainTransport_ConnectResponse:         "PlainTransport_ConnectResponse",
	BodyPlainTransport_DumpResponse:            "PlainTransport_DumpResponse",
	BodyPlainTransport_GetStatsResponse:        "PlainTransport_GetStatsResponse",
	BodyPipeTransport_ConnectResponse:          "PipeTransport_ConnectResponse",
	BodyPipeTransport_DumpResponse:             "PipeTransport_DumpResponse",
	BodyPipeTransport_GetStatsResponse:         "PipeTransport_GetStatsResponse",
	BodyDirectTransport_DumpResponse:           "DirectTransport_DumpResponse",
	BodyDirectTransport_GetStatsResponse:       "DirectTransport_GetStatsResponse",
	BodyWebRtcTransport_ConnectResponse:        "WebRtcTransport_ConnectResponse",
	BodyWebRtcTransport_DumpResponse:           "WebRtcTransport_DumpResponse",
	BodyWebRtcTransport_GetStatsResponse:       "WebRtcTransport_GetStatsResponse",
	BodyProducer_DumpResponse:                  "Producer_DumpResponse",
	BodyProducer_GetStatsResponse:              "Producer_GetStatsResponse",
	BodyConsumer_DumpResponse:                  "Consumer_DumpResponse",
	BodyConsumer_GetStatsResponse:              "Consumer_GetStatsResponse",
	BodyConsumer_SetPreferredLayersResponse:    "Consumer_SetPreferredLayersResponse",
	BodyConsumer_SetPriorityResponse:           "Consumer_SetPriorityResponse",
	BodyDataProducer_DumpResponse:              "DataProducer_DumpResponse",
	BodyDataProducer_GetStatsResponse:          "DataProducer_GetStatsResponse",
	BodyDataConsumer_GetBufferedAmountResponse: "DataConsumer_GetBufferedAmountResponse",
	BodyDataConsumer_DumpResponse:              "DataConsumer_DumpResponse",
	BodyDataConsumer_GetStatsResponse:          "DataConsumer_GetStatsResponse",
	BodyDataConsumer_SetSubchannelsResponse:    "DataConsumer_SetSubchannelsResponse",
	BodyDataConsumer_AddSubchannelResponse:     "DataConsumer_AddSubchannelResponse",
	BodyDataConsumer_RemoveSubchannelResponse:  "DataConsumer_RemoveSubchannelResponse",
}

var EnumValuesBody = map[string]Body{
	"NONE":                                   BodyNONE,
	"Worker_DumpResponse":                    BodyWorker_DumpResponse,
	"Worker_ResourceUsageResponse":           BodyWorker_ResourceUsageResponse,
	"WebRtcServer_DumpResponse":              BodyWebRtcServer_DumpResponse,
	"Router_DumpResponse":                    BodyRouter_DumpResponse,
	"Transport_ProduceResponse":              BodyTransport_ProduceResponse,
	"Transport_ConsumeResponse":              BodyTransport_ConsumeResponse,
	"Transport_RestartIceResponse":           BodyTransport_RestartIceResponse,
	"PlainTransport_ConnectResponse":         BodyPlainTransport_ConnectResponse,
	"PlainTransport_DumpResponse":            BodyPlainTransport_DumpResponse,
	"PlainTransport_GetStatsResponse":        BodyPlainTransport_GetStatsResponse,
	"PipeTransport_ConnectResponse":          BodyPipeTransport_ConnectResponse,
	"PipeTransport_DumpResponse":             BodyPipeTransport_DumpResponse,
	"PipeTransport_GetStatsResponse":         BodyPipeTransport_GetStatsResponse,
	"DirectTransport_DumpResponse":           BodyDirectTransport_DumpResponse,
	"DirectTransport_GetStatsResponse":       BodyDirectTransport_GetStatsResponse,
	"WebRtcTransport_ConnectResponse":        BodyWebRtcTransport_ConnectResponse,
	"WebRtcTransport_DumpResponse":           BodyWebRtcTransport_DumpResponse,
	"WebRtcTransport_GetStatsResponse":       BodyWebRtcTransport_GetStatsResponse,
	"Producer_DumpResponse":                  BodyProducer_DumpResponse,
	"Producer_GetStatsResponse":              BodyProducer_GetStatsResponse,
	"Consumer_DumpResponse":                  BodyConsumer_DumpResponse,
	"Consumer_GetStatsResponse":              BodyConsumer_GetStatsResponse,
	"Consumer_SetPreferredLayersResponse":    BodyConsumer_SetPreferredLayersResponse,
	"Consumer_SetPriorityResponse":           BodyConsumer_SetPriorityResponse,
	"DataProducer_DumpResponse":              BodyDataProducer_DumpResponse,
	"DataProducer_GetStatsResponse":          BodyDataProducer_GetStatsResponse,
	"DataConsumer_GetBufferedAmountResponse": BodyDataConsumer_GetBufferedAmountResponse,
	"DataConsumer_DumpResponse":              BodyDataConsumer_DumpResponse,
	"DataConsumer_GetStatsResponse":          BodyDataConsumer_GetStatsResponse,
	"DataConsumer_SetSubchannelsResponse":    BodyDataConsumer_SetSubchannelsResponse,
	"DataConsumer_AddSubchannelResponse":     BodyDataConsumer_AddSubchannelResponse,
	"DataConsumer_RemoveSubchannelResponse":  BodyDataConsumer_RemoveSubchannelResponse,
}

func (v Body) String() string {
	if s, ok := EnumNamesBody[v]; ok {
		return s
	}
	return "Body(" + strconv.FormatInt(int64(v), 10) + ")"
}
