// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Message

import "strconv"

type Body byte

const (
	BodyNONE         Body = 0
	BodyRequest      Body = 1
	BodyResponse     Body = 2
	BodyNotification Body = 3
	BodyLog          Body = 4
)

var EnumNamesBody = map[Body]string{
	BodyNONE:         "NONE",
	BodyRequest:      "Request",
	BodyResponse:     "Response",
	BodyNotification: "Notification",
	BodyLog:          "Log",
}

var EnumValuesBody = map[string]Body{
	"NONE":         BodyNONE,
	"Request":      BodyRequest,
	"Response":     BodyResponse,
	"Notification": BodyNotification,
	"Log":          BodyLog,
}

func (v Body) String() string {
	if s, ok := EnumNamesBody[v]; ok {
		return s
	}
	return "Body(" + strconv.FormatInt(int64(v), 10) + ")"
}
