// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Consumer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetPreferredLayersResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSetPreferredLayersResponse(buf []byte, offset flatbuffers.UOffsetT) *SetPreferredLayersResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetPreferredLayersResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetPreferredLayersResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetPreferredLayersResponse(buf []byte, offset flatbuffers.UOffsetT) *SetPreferredLayersResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetPreferredLayersResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetPreferredLayersResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetPreferredLayersResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetPreferredLayersResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetPreferredLayersResponse) PreferredLayers(obj *ConsumerLayers) *ConsumerLayers {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ConsumerLayers)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SetPreferredLayersResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SetPreferredLayersResponseAddPreferredLayers(builder *flatbuffers.Builder, preferredLayers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(preferredLayers), 0)
}
func SetPreferredLayersResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
