// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Consumer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetPriorityResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSetPriorityResponse(buf []byte, offset flatbuffers.UOffsetT) *SetPriorityResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetPriorityResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetPriorityResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetPriorityResponse(buf []byte, offset flatbuffers.UOffsetT) *SetPriorityResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetPriorityResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetPriorityResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetPriorityResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetPriorityResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetPriorityResponse) Priority() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SetPriorityResponse) MutatePriority(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func SetPriorityResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SetPriorityResponseAddPriority(builder *flatbuffers.Builder, priority byte) {
	builder.PrependByteSlot(0, priority, 0)
}
func SetPriorityResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
