// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Consumer

import "strconv"

type TraceInfo byte

const (
	TraceInfoNONE              TraceInfo = 0
	TraceInfoKeyFrameTraceInfo TraceInfo = 1
	TraceInfoFirTraceInfo      TraceInfo = 2
	TraceInfoPliTraceInfo      TraceInfo = 3
	TraceInfoRtpTraceInfo      TraceInfo = 4
)

var EnumNamesTraceInfo = map[TraceInfo]string{
	TraceInfoNONE:              "NONE",
	TraceInfoKeyFrameTraceInfo: "KeyFrameTraceInfo",
	TraceInfoFirTraceInfo:      "FirTraceInfo",
	TraceInfoPliTraceInfo:      "PliTraceInfo",
	TraceInfoRtpTraceInfo:      "RtpTraceInfo",
}

var EnumValuesTraceInfo = map[string]TraceInfo{
	"NONE":              TraceInfoNONE,
	"KeyFrameTraceInfo": TraceInfoKeyFrameTraceInfo,
	"FirTraceInfo":      TraceInfoFirTraceInfo,
	"PliTraceInfo":      TraceInfoPliTraceInfo,
	"RtpTraceInfo":      TraceInfoRtpTraceInfo,
}

func (v TraceInfo) String() string {
	if s, ok := EnumNamesTraceInfo[v]; ok {
		return s
	}
	return "TraceInfo(" + strconv.FormatInt(int64(v), 10) + ")"
}
