// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Consumer

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"

	FBS__Consumer "github.com/byyam/mediasoup-go-worker/fbs/FBS/Consumer"
)

type TraceInfoT struct {
	Type TraceInfo
	Value interface{}
}

func (t *TraceInfoT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case TraceInfoKeyFrameTraceInfo:
		return t.Value.(*FBS__Consumer.KeyFrameTraceInfoT).Pack(builder)
	case TraceInfoFirTraceInfo:
		return t.Value.(*FBS__Consumer.FirTraceInfoT).Pack(builder)
	case TraceInfoPliTraceInfo:
		return t.Value.(*FBS__Consumer.PliTraceInfoT).Pack(builder)
	case TraceInfoRtpTraceInfo:
		return t.Value.(*FBS__Consumer.RtpTraceInfoT).Pack(builder)
	}
	return 0
}

func (rcv TraceInfo) UnPack(table flatbuffers.Table) *TraceInfoT {
	switch rcv {
	case TraceInfoKeyFrameTraceInfo:
		var x FBS__Consumer.KeyFrameTraceInfo
		x.Init(table.Bytes, table.Pos)
		return &FBS__Consumer.TraceInfoT{Type: TraceInfoKeyFrameTraceInfo, Value: x.UnPack()}
	case TraceInfoFirTraceInfo:
		var x FBS__Consumer.FirTraceInfo
		x.Init(table.Bytes, table.Pos)
		return &FBS__Consumer.TraceInfoT{Type: TraceInfoFirTraceInfo, Value: x.UnPack()}
	case TraceInfoPliTraceInfo:
		var x FBS__Consumer.PliTraceInfo
		x.Init(table.Bytes, table.Pos)
		return &FBS__Consumer.TraceInfoT{Type: TraceInfoPliTraceInfo, Value: x.UnPack()}
	case TraceInfoRtpTraceInfo:
		var x FBS__Consumer.RtpTraceInfo
		x.Init(table.Bytes, table.Pos)
		return &FBS__Consumer.TraceInfoT{Type: TraceInfoRtpTraceInfo, Value: x.UnPack()}
	}
	return nil
}
