// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Worker

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChannelMessageHandlers struct {
	_tab flatbuffers.Table
}

func GetRootAsChannelMessageHandlers(buf []byte, offset flatbuffers.UOffsetT) *ChannelMessageHandlers {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChannelMessageHandlers{}
	x.Init(buf, n+offset)
	return x
}

func FinishChannelMessageHandlersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChannelMessageHandlers(buf []byte, offset flatbuffers.UOffsetT) *ChannelMessageHandlers {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChannelMessageHandlers{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChannelMessageHandlersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChannelMessageHandlers) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChannelMessageHandlers) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChannelMessageHandlers) ChannelRequestHandlers(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *ChannelMessageHandlers) ChannelRequestHandlersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChannelMessageHandlers) ChannelNotificationHandlers(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *ChannelMessageHandlers) ChannelNotificationHandlersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ChannelMessageHandlersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ChannelMessageHandlersAddChannelRequestHandlers(builder *flatbuffers.Builder, channelRequestHandlers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(channelRequestHandlers), 0)
}
func ChannelMessageHandlersStartChannelRequestHandlersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ChannelMessageHandlersAddChannelNotificationHandlers(builder *flatbuffers.Builder, channelNotificationHandlers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(channelNotificationHandlers), 0)
}
func ChannelMessageHandlersStartChannelNotificationHandlersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ChannelMessageHandlersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
