// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtpStream

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"

	FBS__RtpStream "github.com/byyam/mediasoup-go-worker/fbs/FBS/RtpStream"
)

type StatsDataT struct {
	Type StatsData
	Value interface{}
}

func (t *StatsDataT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case StatsDataBaseStats:
		return t.Value.(*FBS__RtpStream.BaseStatsT).Pack(builder)
	case StatsDataRecvStats:
		return t.Value.(*FBS__RtpStream.RecvStatsT).Pack(builder)
	case StatsDataSendStats:
		return t.Value.(*FBS__RtpStream.SendStatsT).Pack(builder)
	}
	return 0
}

func (rcv StatsData) UnPack(table flatbuffers.Table) *StatsDataT {
	switch rcv {
	case StatsDataBaseStats:
		var x FBS__RtpStream.BaseStats
		x.Init(table.Bytes, table.Pos)
		return &FBS__RtpStream.StatsDataT{Type: StatsDataBaseStats, Value: x.UnPack()}
	case StatsDataRecvStats:
		var x FBS__RtpStream.RecvStats
		x.Init(table.Bytes, table.Pos)
		return &FBS__RtpStream.StatsDataT{Type: StatsDataRecvStats, Value: x.UnPack()}
	case StatsDataSendStats:
		var x FBS__RtpStream.SendStats
		x.Init(table.Bytes, table.Pos)
		return &FBS__RtpStream.StatsDataT{Type: StatsDataSendStats, Value: x.UnPack()}
	}
	return nil
}
