// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Request

import "strconv"

type Body byte

const (
	BodyNONE                                              Body = 0
	BodyWorker_UpdateSettingsRequest                      Body = 1
	BodyWorker_CreateWebRtcServerRequest                  Body = 2
	BodyWorker_CloseWebRtcServerRequest                   Body = 3
	BodyWorker_CreateRouterRequest                        Body = 4
	BodyWorker_CloseRouterRequest                         Body = 5
	BodyRouter_CreateWebRtcTransportRequest               Body = 6
	BodyRouter_CreatePlainTransportRequest                Body = 7
	BodyRouter_CreatePipeTransportRequest                 Body = 8
	BodyRouter_CreateDirectTransportRequest               Body = 9
	BodyRouter_CreateActiveSpeakerObserverRequest         Body = 10
	BodyRouter_CreateAudioLevelObserverRequest            Body = 11
	BodyRouter_CloseTransportRequest                      Body = 12
	BodyRouter_CloseRtpObserverRequest                    Body = 13
	BodyTransport_SetMaxIncomingBitrateRequest            Body = 14
	BodyTransport_SetMaxOutgoingBitrateRequest            Body = 15
	BodyTransport_SetMinOutgoingBitrateRequest            Body = 16
	BodyTransport_ProduceRequest                          Body = 17
	BodyTransport_ConsumeRequest                          Body = 18
	BodyTransport_ProduceDataRequest                      Body = 19
	BodyTransport_ConsumeDataRequest                      Body = 20
	BodyTransport_EnableTraceEventRequest                 Body = 21
	BodyTransport_CloseProducerRequest                    Body = 22
	BodyTransport_CloseConsumerRequest                    Body = 23
	BodyTransport_CloseDataProducerRequest                Body = 24
	BodyTransport_CloseDataConsumerRequest                Body = 25
	BodyPlainTransport_ConnectRequest                     Body = 26
	BodyPipeTransport_ConnectRequest                      Body = 27
	BodyWebRtcTransport_ConnectRequest                    Body = 28
	BodyProducer_EnableTraceEventRequest                  Body = 29
	BodyConsumer_SetPreferredLayersRequest                Body = 30
	BodyConsumer_SetPriorityRequest                       Body = 31
	BodyConsumer_EnableTraceEventRequest                  Body = 32
	BodyDataConsumer_SetBufferedAmountLowThresholdRequest Body = 33
	BodyDataConsumer_SendRequest                          Body = 34
	BodyDataConsumer_SetSubchannelsRequest                Body = 35
	BodyDataConsumer_AddSubchannelRequest                 Body = 36
	BodyDataConsumer_RemoveSubchannelRequest              Body = 37
	BodyRtpObserver_AddProducerRequest                    Body = 38
	BodyRtpObserver_RemoveProducerRequest                 Body = 39
)

var EnumNamesBody = map[Body]string{
	BodyNONE:                                              "NONE",
	BodyWorker_UpdateSettingsRequest:                      "Worker_UpdateSettingsRequest",
	BodyWorker_CreateWebRtcServerRequest:                  "Worker_CreateWebRtcServerRequest",
	BodyWorker_CloseWebRtcServerRequest:                   "Worker_CloseWebRtcServerRequest",
	BodyWorker_CreateRouterRequest:                        "Worker_CreateRouterRequest",
	BodyWorker_CloseRouterRequest:                         "Worker_CloseRouterRequest",
	BodyRouter_CreateWebRtcTransportRequest:               "Router_CreateWebRtcTransportRequest",
	BodyRouter_CreatePlainTransportRequest:                "Router_CreatePlainTransportRequest",
	BodyRouter_CreatePipeTransportRequest:                 "Router_CreatePipeTransportRequest",
	BodyRouter_CreateDirectTransportRequest:               "Router_CreateDirectTransportRequest",
	BodyRouter_CreateActiveSpeakerObserverRequest:         "Router_CreateActiveSpeakerObserverRequest",
	BodyRouter_CreateAudioLevelObserverRequest:            "Router_CreateAudioLevelObserverRequest",
	BodyRouter_CloseTransportRequest:                      "Router_CloseTransportRequest",
	BodyRouter_CloseRtpObserverRequest:                    "Router_CloseRtpObserverRequest",
	BodyTransport_SetMaxIncomingBitrateRequest:            "Transport_SetMaxIncomingBitrateRequest",
	BodyTransport_SetMaxOutgoingBitrateRequest:            "Transport_SetMaxOutgoingBitrateRequest",
	BodyTransport_SetMinOutgoingBitrateRequest:            "Transport_SetMinOutgoingBitrateRequest",
	BodyTransport_ProduceRequest:                          "Transport_ProduceRequest",
	BodyTransport_ConsumeRequest:                          "Transport_ConsumeRequest",
	BodyTransport_ProduceDataRequest:                      "Transport_ProduceDataRequest",
	BodyTransport_ConsumeDataRequest:                      "Transport_ConsumeDataRequest",
	BodyTransport_EnableTraceEventRequest:                 "Transport_EnableTraceEventRequest",
	BodyTransport_CloseProducerRequest:                    "Transport_CloseProducerRequest",
	BodyTransport_CloseConsumerRequest:                    "Transport_CloseConsumerRequest",
	BodyTransport_CloseDataProducerRequest:                "Transport_CloseDataProducerRequest",
	BodyTransport_CloseDataConsumerRequest:                "Transport_CloseDataConsumerRequest",
	BodyPlainTransport_ConnectRequest:                     "PlainTransport_ConnectRequest",
	BodyPipeTransport_ConnectRequest:                      "PipeTransport_ConnectRequest",
	BodyWebRtcTransport_ConnectRequest:                    "WebRtcTransport_ConnectRequest",
	BodyProducer_EnableTraceEventRequest:                  "Producer_EnableTraceEventRequest",
	BodyConsumer_SetPreferredLayersRequest:                "Consumer_SetPreferredLayersRequest",
	BodyConsumer_SetPriorityRequest:                       "Consumer_SetPriorityRequest",
	BodyConsumer_EnableTraceEventRequest:                  "Consumer_EnableTraceEventRequest",
	BodyDataConsumer_SetBufferedAmountLowThresholdRequest: "DataConsumer_SetBufferedAmountLowThresholdRequest",
	BodyDataConsumer_SendRequest:                          "DataConsumer_SendRequest",
	BodyDataConsumer_SetSubchannelsRequest:                "DataConsumer_SetSubchannelsRequest",
	BodyDataConsumer_AddSubchannelRequest:                 "DataConsumer_AddSubchannelRequest",
	BodyDataConsumer_RemoveSubchannelRequest:              "DataConsumer_RemoveSubchannelRequest",
	BodyRtpObserver_AddProducerRequest:                    "RtpObserver_AddProducerRequest",
	BodyRtpObserver_RemoveProducerRequest:                 "RtpObserver_RemoveProducerRequest",
}

var EnumValuesBody = map[string]Body{
	"NONE":                                              BodyNONE,
	"Worker_UpdateSettingsRequest":                      BodyWorker_UpdateSettingsRequest,
	"Worker_CreateWebRtcServerRequest":                  BodyWorker_CreateWebRtcServerRequest,
	"Worker_CloseWebRtcServerRequest":                   BodyWorker_CloseWebRtcServerRequest,
	"Worker_CreateRouterRequest":                        BodyWorker_CreateRouterRequest,
	"Worker_CloseRouterRequest":                         BodyWorker_CloseRouterRequest,
	"Router_CreateWebRtcTransportRequest":               BodyRouter_CreateWebRtcTransportRequest,
	"Router_CreatePlainTransportRequest":                BodyRouter_CreatePlainTransportRequest,
	"Router_CreatePipeTransportRequest":                 BodyRouter_CreatePipeTransportRequest,
	"Router_CreateDirectTransportRequest":               BodyRouter_CreateDirectTransportRequest,
	"Router_CreateActiveSpeakerObserverRequest":         BodyRouter_CreateActiveSpeakerObserverRequest,
	"Router_CreateAudioLevelObserverRequest":            BodyRouter_CreateAudioLevelObserverRequest,
	"Router_CloseTransportRequest":                      BodyRouter_CloseTransportRequest,
	"Router_CloseRtpObserverRequest":                    BodyRouter_CloseRtpObserverRequest,
	"Transport_SetMaxIncomingBitrateRequest":            BodyTransport_SetMaxIncomingBitrateRequest,
	"Transport_SetMaxOutgoingBitrateRequest":            BodyTransport_SetMaxOutgoingBitrateRequest,
	"Transport_SetMinOutgoingBitrateRequest":            BodyTransport_SetMinOutgoingBitrateRequest,
	"Transport_ProduceRequest":                          BodyTransport_ProduceRequest,
	"Transport_ConsumeRequest":                          BodyTransport_ConsumeRequest,
	"Transport_ProduceDataRequest":                      BodyTransport_ProduceDataRequest,
	"Transport_ConsumeDataRequest":                      BodyTransport_ConsumeDataRequest,
	"Transport_EnableTraceEventRequest":                 BodyTransport_EnableTraceEventRequest,
	"Transport_CloseProducerRequest":                    BodyTransport_CloseProducerRequest,
	"Transport_CloseConsumerRequest":                    BodyTransport_CloseConsumerRequest,
	"Transport_CloseDataProducerRequest":                BodyTransport_CloseDataProducerRequest,
	"Transport_CloseDataConsumerRequest":                BodyTransport_CloseDataConsumerRequest,
	"PlainTransport_ConnectRequest":                     BodyPlainTransport_ConnectRequest,
	"PipeTransport_ConnectRequest":                      BodyPipeTransport_ConnectRequest,
	"WebRtcTransport_ConnectRequest":                    BodyWebRtcTransport_ConnectRequest,
	"Producer_EnableTraceEventRequest":                  BodyProducer_EnableTraceEventRequest,
	"Consumer_SetPreferredLayersRequest":                BodyConsumer_SetPreferredLayersRequest,
	"Consumer_SetPriorityRequest":                       BodyConsumer_SetPriorityRequest,
	"Consumer_EnableTraceEventRequest":                  BodyConsumer_EnableTraceEventRequest,
	"DataConsumer_SetBufferedAmountLowThresholdRequest": BodyDataConsumer_SetBufferedAmountLowThresholdRequest,
	"DataConsumer_SendRequest":                          BodyDataConsumer_SendRequest,
	"DataConsumer_SetSubchannelsRequest":                BodyDataConsumer_SetSubchannelsRequest,
	"DataConsumer_AddSubchannelRequest":                 BodyDataConsumer_AddSubchannelRequest,
	"DataConsumer_RemoveSubchannelRequest":              BodyDataConsumer_RemoveSubchannelRequest,
	"RtpObserver_AddProducerRequest":                    BodyRtpObserver_AddProducerRequest,
	"RtpObserver_RemoveProducerRequest":                 BodyRtpObserver_RemoveProducerRequest,
}

func (v Body) String() string {
	if s, ok := EnumNamesBody[v]; ok {
		return s
	}
	return "Body(" + strconv.FormatInt(int64(v), 10) + ")"
}
