// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Transport

import (
	flatbuffers "github.com/google/flatbuffers/go"

	FBS__DataProducer "FBS/DataProducer"
	FBS__SctpParameters "FBS/SctpParameters"
)

type ConsumeDataRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsConsumeDataRequest(buf []byte, offset flatbuffers.UOffsetT) *ConsumeDataRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConsumeDataRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishConsumeDataRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConsumeDataRequest(buf []byte, offset flatbuffers.UOffsetT) *ConsumeDataRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConsumeDataRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConsumeDataRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConsumeDataRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConsumeDataRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConsumeDataRequest) DataConsumerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConsumeDataRequest) DataProducerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConsumeDataRequest) Type() FBS__DataProducer.Type {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return FBS__DataProducer.Type(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ConsumeDataRequest) MutateType(n FBS__DataProducer.Type) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *ConsumeDataRequest) SctpStreamParameters(obj *FBS__SctpParameters.SctpStreamParameters) *FBS__SctpParameters.SctpStreamParameters {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FBS__SctpParameters.SctpStreamParameters)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ConsumeDataRequest) Label() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConsumeDataRequest) Protocol() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConsumeDataRequest) Paused() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ConsumeDataRequest) MutatePaused(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *ConsumeDataRequest) Subchannels(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *ConsumeDataRequest) SubchannelsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ConsumeDataRequest) MutateSubchannels(j int, n uint16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateUint16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func ConsumeDataRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func ConsumeDataRequestAddDataConsumerId(builder *flatbuffers.Builder, dataConsumerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataConsumerId), 0)
}
func ConsumeDataRequestAddDataProducerId(builder *flatbuffers.Builder, dataProducerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(dataProducerId), 0)
}
func ConsumeDataRequestAddType(builder *flatbuffers.Builder, type_ FBS__DataProducer.Type) {
	builder.PrependByteSlot(2, byte(type_), 0)
}
func ConsumeDataRequestAddSctpStreamParameters(builder *flatbuffers.Builder, sctpStreamParameters flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(sctpStreamParameters), 0)
}
func ConsumeDataRequestAddLabel(builder *flatbuffers.Builder, label flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(label), 0)
}
func ConsumeDataRequestAddProtocol(builder *flatbuffers.Builder, protocol flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(protocol), 0)
}
func ConsumeDataRequestAddPaused(builder *flatbuffers.Builder, paused bool) {
	builder.PrependBoolSlot(6, paused, false)
}
func ConsumeDataRequestAddSubchannels(builder *flatbuffers.Builder, subchannels flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(subchannels), 0)
}
func ConsumeDataRequestStartSubchannelsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func ConsumeDataRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
