// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Transport

import "strconv"

type TraceInfo byte

const (
	TraceInfoNONE         TraceInfo = 0
	TraceInfoBweTraceInfo TraceInfo = 1
)

var EnumNamesTraceInfo = map[TraceInfo]string{
	TraceInfoNONE:         "NONE",
	TraceInfoBweTraceInfo: "BweTraceInfo",
}

var EnumValuesTraceInfo = map[string]TraceInfo{
	"NONE":         TraceInfoNONE,
	"BweTraceInfo": TraceInfoBweTraceInfo,
}

func (v TraceInfo) String() string {
	if s, ok := EnumNamesTraceInfo[v]; ok {
		return s
	}
	return "TraceInfo(" + strconv.FormatInt(int64(v), 10) + ")"
}
