// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebRtcTransport

import "strconv"

type Listen byte

const (
	ListenNONE             Listen = 0
	ListenListenIndividual Listen = 1
	ListenListenServer     Listen = 2
)

var EnumNamesListen = map[Listen]string{
	ListenNONE:             "NONE",
	ListenListenIndividual: "ListenIndividual",
	ListenListenServer:     "ListenServer",
}

var EnumValuesListen = map[string]Listen{
	"NONE":             ListenNONE,
	"ListenIndividual": ListenListenIndividual,
	"ListenServer":     ListenListenServer,
}

func (v Listen) String() string {
	if s, ok := EnumNamesListen[v]; ok {
		return s
	}
	return "Listen(" + strconv.FormatInt(int64(v), 10) + ")"
}
