// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package WebRtcTransport

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListenServer struct {
	_tab flatbuffers.Table
}

func GetRootAsListenServer(buf []byte, offset flatbuffers.UOffsetT) *ListenServer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListenServer{}
	x.Init(buf, n+offset)
	return x
}

func FinishListenServerBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsListenServer(buf []byte, offset flatbuffers.UOffsetT) *ListenServer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListenServer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedListenServerBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ListenServer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListenServer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListenServer) WebRtcServerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ListenServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ListenServerAddWebRtcServerId(builder *flatbuffers.Builder, webRtcServerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(webRtcServerId), 0)
}
func ListenServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
