// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package RtpParameters

import "strconv"

type Value byte

const (
	ValueNONE           Value = 0
	ValueBoolean        Value = 1
	ValueInteger32      Value = 2
	ValueDouble         Value = 3
	ValueString         Value = 4
	ValueInteger32Array Value = 5
)

var EnumNamesValue = map[Value]string{
	ValueNONE:           "NONE",
	ValueBoolean:        "Boolean",
	ValueInteger32:      "Integer32",
	ValueDouble:         "Double",
	ValueString:         "String",
	ValueInteger32Array: "Integer32Array",
}

var EnumValuesValue = map[string]Value{
	"NONE":           ValueNONE,
	"Boolean":        ValueBoolean,
	"Integer32":      ValueInteger32,
	"Double":         ValueDouble,
	"String":         ValueString,
	"Integer32Array": ValueInteger32Array,
}

func (v Value) String() string {
	if s, ok := EnumNamesValue[v]; ok {
		return s
	}
	return "Value(" + strconv.FormatInt(int64(v), 10) + ")"
}
